pre-commit:
  parallel: true
  commands:
    biome-check:
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
      run: npx @biomejs/biome check --write {staged_files}
    gitleaks:
      run: gitleaks protect --staged -v
    lychee:
      glob: "*.md"
      run: lychee {staged_files}

commit-msg:
  commands:
    commitlint:
      run: npx commitlint --edit {1}
